name             'kitchenplan-user'
maintainer       'Stefano Zanella'
maintainer_email 'zanella.stefano@gmail.com'
license          'all_rights'
description      'Installs/Configures kitchenplan-user'
long_description 'Installs/Configures kitchenplan-user'
version          '0.1.0'
